//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由EntityGen生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Savory.Repository.TransformDB.Entity
{
    [Table("Template")]
    public partial class TemplateEntity
    {

        /// <summary>
        /// 自增长主键
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// 模版名称
        /// </summary>
        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        /// <summary>
        /// 版本号
        /// </summary>
        [Required]
        [StringLength(20)]
        public string Version { get; set; }

        /// <summary>
        /// 模版内容
        /// </summary>
        [Required]
        public string Body { get; set; }

        /// <summary>
        /// 扩展属性，用于参与编译
        /// </summary>
        [Required]
        public string Extension { get; set; }

        /// <summary>
        /// 示例模版参数
        /// </summary>
        [Required]
        public string ItemJsonValue { get; set; }

        /// <summary>
        /// 描述。例如更次修改的内容
        /// </summary>
        [Required]
        [StringLength(200)]
        public string Description { get; set; }

        /// <summary>
        /// 数据状态
        /// </summary>
        public int DataStatus { get; set; }

        /// <summary>
        /// 创建人
        /// </summary>
        [Required]
        [StringLength(50)]
        public string CreateUser { get; set; }

        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime CreateTime { get; set; }

        /// <summary>
        /// 最后更新人
        /// </summary>
        [Required]
        [StringLength(50)]
        public string LastUpdateUser { get; set; }

        /// <summary>
        /// 最后更新时间
        /// </summary>
        public DateTime LastUpdateTime { get; set; }
    }
}